spring:
  thymeleaf:
    cache: false
  profiles:
    active: pro
#开启驼峰命名匹配映射
mybatis:
  #扫描mapper文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chenxurui.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.chenxurui.dao: debug

comment.avatar: /images/avatar.png
